spring:
  application:
    name: taskmanagement
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.data.jpa.autoconfigure.JpaRepositoriesAutoConfiguration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
